name: "Test run"
on:
  push: {}
  pull_request:
    types: 
      - closed
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run the action
      id: runs
      uses: ./
    - name: Print the output
      run: echo ${{ steps.runs.outputs.env }}
